=== rgmprabodha/Internship_Testing_Projects/JSchemaTest/target/classes/user-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": [],
    "additionalItems": true,
    "items": {
        "$id": "#/items",
        "type": "object",
        "required": [
            "id",
            "firstname",
            "lastname",
            "mail",
            "phone",
            "institution"
        ],
        "additionalProperties": true,
        "properties": {
            "id": {
                "$id": "#/items/properties/id",
                "type": "integer"
            },
            "firstname": {
                "$id": "#/items/properties/firstname",
                "type": "string"
            },
            "lastname": {
                "$id": "#/items/properties/lastname",
                "type": "string"
            },
            "mail": {
                "$id": "#/items/properties/mail",
                "type": "string"
            },
            "phone": {
                "$id": "#/items/properties/phone",
                "type": "string"
            },
            "institution": {
                "$id": "#/items/properties/institution",
                "type": "string"
            }
        }            
    }
}

=== rgmprabodha/Internship_Testing_Projects/JSchemaTest/target/classes/user.json
[{
    "id": 0,
    "firstname": "Malshani",
    "lastname": "RG",
    "mail": "malshani@rg.com",
    "phone": "+33612345678",
    "institution": "EMSE"
},
{
    "id": 1,
    "firstname": "Dishan",
    "lastname": "PG",
    "mail": "dishan@pg.com",
    "phone": "+33612345678",
    "institution": "UCSC"
}]
