=== rgmprabodha/Internship_Testing_Projects/GenerateShape/src/main/resources/office/office-schema-generated.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "required": [
        "id",
        "label",
        "floor",
        "area",
        "sensors",
        "geometry"
    ],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "integer",
            "maximum": 4
        },
        "label": {
            "$id": "#/properties/label",
            "type": "string"
        },
        "floor": {
            "$id": "#/properties/floor",
            "type": "integer",
            "exclusiveMaximum": 4
        },
        "area": {
            "$id": "#/properties/area",
            "type": "number",
            "maximum": 24,
            "minimum": 1
        },
        "sensors": {
            "$id": "#/properties/sensors",
            "type": "integer",
            "exclusiveMinimum": 0
        },
        "geometry": {
            "$id": "#/properties/geometry",
            "type": "object",
            "required": [
                "type",
                "projection",
                "coordinates"
            ],
            "properties": {
                "type": {
                    "$id": "#/properties/geometry/properties/type",
                    "type": "string"
                },
                "projection": {
                    "$id": "#/properties/geometry/properties/projection",
                    "type": "string"
                },
                "coordinates": {
                    "$id": "#/properties/geometry/properties/coordinates",
                    "type": "array",
                    "additionalItems": false,
                    "items": {
                        "$id": "#/properties/geometry/properties/coordinates/items",             
                        "type": "object",
                        "required": [
                            "type",
                            "projection",
                            "coordinates"
                        ],
                        "properties": {
                            "type": {
                                "$id": "#/properties/geometry/properties/coordinates/items/anyOf/0/properties/type",
                                "type": "string"
                            },
                            "projection": {
                                "$id": "#/properties/geometry/properties/coordinates/items/anyOf/0/properties/projection",
                                "type": "string"
                            },
                            "coordinates": {
                                "$id": "#/properties/geometry/properties/coordinates/items/anyOf/0/properties/coordinates",
                                "type": "object",
                                "required": [
                                    "latitude",
                                    "longitude"
                                ],
                                "properties": {
                                    "latitude": {
                                        "$id": "#/properties/geometry/properties/coordinates/items/anyOf/0/properties/coordinates/properties/latitude",
                                        "type": "number"
                                    },
                                    "longitude": {
                                        "$id": "#/properties/geometry/properties/coordinates/items/anyOf/0/properties/coordinates/properties/longitude",
                                        "type": "number"
                                    }
                                },
                                "additionalProperties": true
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== rgmprabodha/Internship_Testing_Projects/GenerateShape/target/classes/office/office-data.json
{
    "id": 0,
    "label": "string",
    "floor": 0,
    "area": 5,
    "sensors": 3,
    "geometry": {
      "type": "string",
      "projection": "string",
      "coordinates": [
        {
          "type": "string",
          "projection": "string",
          "coordinates": {
            "latitude": 0,
            "longitude": 0
          }
        }
      ]
    }
}
